name = "Ted Kitch"
description = "Husband, father and occasional knucklehead"
keywords = "Ted Kitch, knucklehead"
image = "MyProfilePic.png"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = ""
base_url = "https://tedkitch.github.io/tedkitch"

[[sections]]
title = "Hobbies"
description = "Some of my hobbies"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Computers"
description = "I've been using computers since the Commodore Vic 20"
url = "https://en.wikipedia.org/wiki/VIC-20"
[[sections.items]]
title = "Guitars"
description = "I've been playing since I was 13"
url = "https://en.wikipedia.org/wiki/Kramer_Guitars"
[[sections.items]]
title = "Church"
description = "I've been a member of The Church of Jesus Christ of Latter-Day Saints since 1989"
url = "https://en.wikipedia.org/wiki/The_Church_of_Jesus_Christ_of_Latter-day_Saints"
